export const OVERS = [
  { value: 3, label: "Quick Match", desc: "3 Overs" },
  { value: 5, label: "Short Game", desc: "5 Overs" },
  { value: 10, label: "Standard", desc: "10 Overs" },
  { value: 20, label: "Full Match", desc: "20 Overs" },
];

export const TEAM_COLORS = [
  "from-blue-600 to-saffron-500",
  "from-yellow-500 to-green-600",
  "from-green-500 to-white",
  "from-red-600 to-blue-700",
  "from-black to-slate-700",
  "from-green-600 to-yellow-500",
  "from-blue-700 to-orange-600",
  "from-red-500 to-green-600",
  "from-maroon-600 to-gold-500",
  "from-black to-green-600",
  "from-blue-500 to-white",
  "from-green-700 to-yellow-500",
  "from-orange-600 to-red-600",
  "from-red-700 to-blue-700",
  "from-green-600 to-white",
  "from-blue-800 to-red-800",
  "from-red-500 to-black",
  "from-green-800 to-white",
  "from-red-700 to-white",
  "from-blue-500 to-red-500",
];

export const needThisTeam = [
  "India",
  "Sri Lanka",
  "Afghanistan",
  "Australia",
  "Bangladesh",
  "England",
  "South Africa",
  "United States",
  "West Indies",
  "Ireland",
  "New Zealand",
  "Pakistan",
  "Canada",
  "Italy",
  "Netherlands",
  "Namibia",
  "Zimbabwe",
  "Nepal",
  "Oman",
  "United Arab Emirates",
];
